name: saferide_parent
description: "SafeRide Tracking & Safety System - Parent Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase Core saha Database
  firebase_core: ^3.10.1
  firebase_database: ^11.3.10

  # Google Maps saha Location tracking
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  firebase_auth: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/ai_logs_card.jpg
    - assets/attendance_card.jpg
    - assets/driver_card.jpg
    - assets/tracking_card.jpg
    - assets/parent.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/parent.png" # Oyaage image eke name eka methanata danna